[package]
name = "persistent-loadout"
version = "0.2.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.64"
xplm = "0.4.1"
xplm-sys = "0.5.0"
