[package]
name = "persistent-loadout"
version = "0.4.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
thiserror = "2.0.3"
xplm = "0.4.1"
xplm-sys = "0.5.0"
