[package]
name = "persistent-loadout"
version = "0.5.3"
edition = "2021"
publish = false
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
thiserror = "1.0.69"
xplm = "0.4.2"
xplm-sys = "0.5.1"
