name: CI

on:
  pull_request:
    paths:
      - src/**/*
      - Cargo.toml
      - Cross.toml

jobs:
  clippy:
    runs-on: ubuntu-latest

    # Make sure CI fails on all warnings, including Clippy lints
    env:
      RUSTFLAGS: "-Dwarnings"

    steps:
      - uses: actions/checkout@v4

      - name: Clippy
        run: |
          cargo clippy --all-targets --all-features

  build-linux:
    runs-on: ubuntu-latest

    needs: clippy

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make build/linux

      - uses: actions/upload-artifact@v4
        with:
          name: lin_x64
          path: |
            persistent-loadout

  build-mac:
    runs-on: macos-latest

    needs: clippy

    steps:
      - uses: actions/checkout@v4

      - name: rustup target add
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin

      - name: Build
        run: make build/mac

      - uses: actions/upload-artifact@v4
        with:
          name: mac_x64
          path: |
            persistent-loadout

  build-windows:
    runs-on: ubuntu-latest

    needs: clippy

    steps:
      - uses: actions/checkout@v4

      - name: Install Cross
        run: cargo install cross

      - name: Build
        run: make build/windows

      - uses: actions/upload-artifact@v4
        with:
          name: win_x64
          path: |
            persistent-loadout
