name: ci.yml

on:
  workflow_dispatch:
  pull_request:
    paths:
      - src/**/*
      - Cargo.toml

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      output-path: persistent_loadout
