name: Release Workflow

on:
  pull_request:
    paths:
      - src/**
      - Cargo.toml
      - Cross.toml

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make build/linux

      - uses: actions/upload-artifact@v4
        with:
          name: lin_x64
          path: |
            persistent-loadout

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: rustup target add
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin

      - name: Build
        run: make build/mac

      - uses: actions/upload-artifact@v4
        with:
          name: mac_x64
          path: |
            persistent-loadout

  build-windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Cross
        run: cargo install cross

      - name: Build
        run: make build/windows

      - uses: actions/upload-artifact@v4
        with:
          name: win_x64
          path: |
            persistent-loadout
