name: Release

on:
  push:
    branches: [ "add-release-workflow" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Cross
        run: cargo install cross

      - name: Build
        run: make build/all

      - name: Create ZIP archive
        env:
          tag_name: ${{ github.ref_name }}
        run: zip -r persistent-loadout-${tag_name}.zip persistent-loadout/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: persistent-loadout-*.zip
